// Generated by CodeFlow
// Created at Fri Jun 14 2019 10:14:17 GMT+0000 (UTC)
// Created by d00187959

@Library('codeflow') _
node("mesos") {
    stage("init") {
        cloudBuildConfig {
            group_id = "gf39c4b51a6684f1fa3f283a3ae42cc48"
            service_id = "c8a59cec951743e693a72b884c4ea3c6"
            project_id = "4ce76a7c9fa5416ea5489a0b8855b593"
            project_name = "HMSWallet"
        }
    }

    cloudBuild {
        jobs = [
            "codingstylecheck":{
            },
            "findbugs":{
            },
            "pmd":{
            },
            "cmetrics":{
                        expect(report.maximum_cyclomatic_complexity).lessOrEqual(15)
                        expect(report.cyclomatic_complexity_per_method).lessOrEqual(5)
                        expect(report.code_duplication_ratio).lessOrEqual(5)
                        expect(report.dangerous_funcs_total).lessOrEqual(0)
                        expect(report.file_duplication_ratio).lessOrEqual(0.5)
            },
        ]
    }

}

